export enum UserInformation {
    USERNAME_REQUIRED = "O nome do usuário é obrigatório.",
    EMAIL_REQUIRED = "O email é obrigatório.",
    PASSWORD_REQUIRED = "A senha é obrigatória.",
    CITY_REQUIRED = "A cidade é obrigatória.",
    STATE_REQUIRED = "O estado é obrigatório.",
    USER_WITH_TEAM = "Apenas usuários sem equipe podem ser promovidos a administrador.",
    USER_WITHOUT_TEAM = "O usuário não pertence a uma equipe.",
    NEW_USER = "Novo usuário",
    TEAM_ADMIN = "Administrador da equipe",
    TEAM_MEMBER = "Membro da equipe",
    SYSTEM_ADMIN = "Administrador do sistema",
    ROLE_UNKNOWN = "Permissão desconhecida",
    EMAIL_ALREADY_REGISTERED = "Email já cadastrado.",
    USER_NOT_FOUND = "Usuário não encontrado.",
    USER_DELETED = "Usuário excluído.",
    USER_INACTIVE = "Usuário inativo.",
    USER_ACTIVE = "Usuário ativo.",
    USER_REACTIVATED = "Usuário reativado com sucesso.",
    USER_CREATED = "Usuário criado com sucesso.",
    USER_PROMOTED_ADM = "Usuário promovido a administrador da equipe com sucesso.",
    USER_JOINED_TEAM = "Usuário entrou na equipe com sucesso.",
}